cargo-features = [ "per-package-target" ]

[package]
name = "mars_bootloader"
version = "0.0.1"
edition = "2024"
default-target = "aarch64-unknown-uefi"

[dependencies]
log = "0.4.29"
uefi = { version = "0.36.1", features = ["logger", "panic_handler"] }
