[target.aarch64-unknown-none]
rustflags = [
    "-C", "link-arg=-static",
    "-C", "relocation-model=static",
]
runner = "./qemu-arm.sh"

[target.aarch64-unknown-uefi]
rustflags = [
    "-C", "link-arg=-pie",
    "-C", "relocation-model=pie",
]
